"""Atlas AI Daily Site Report Generator (PX-02 Phase 3).

Pure composition over existing engines - zero new collections, per
this task's own explicit constraint. Every count and financial value
in this report is computed directly from real, already-stored data
(operational_items, events, commercial_events, ai_analyses) - never
estimated, inferred, or generated by an LLM.

A deliberate design choice, stated here and repeated in
OPERATIONAL_REASONING_NOTES.md: every "narrative" section in this
report (Executive Summary, AI Forecast Impact) is deterministic,
template-composed text built from the same real computed values the
structured sections use - not an LLM call. This task explicitly warns
against fabricating operational facts or precise forecasts; the
strongest possible guarantee against that is not calling an LLM at
all for this report, rather than calling one and hoping it doesn't
invent something. "AI-generated" in this report means: assembled by
Atlas's own deterministic reasoning over data it already trusts, the
same discipline CRE's own evaluate_rules already uses - not natural
language generation.
"""
from __future__ import annotations
from datetime import datetime, timezone, timedelta
from typing import Optional
from core.db import db
from engines import memory_engine, commercial_engine, reasoning_engine

IMPACT_CATEGORIES = ("schedule", "quality", "cost", "safety", "client_decision")

_CATEGORY_TO_IMPACT = {
    "material_requirement": "schedule", "labour_requirement": "schedule",
    "equipment_requirement": "schedule", "client_approval": "client_decision",
    "drawing_request": "schedule", "site_issue": "quality",
    "quality_observation": "quality", "safety_observation": "safety",
    "commitment": "schedule", "inspection": "quality",
    "follow_up": "schedule", "general": "schedule",
}


def _day_bounds(target_date: str) -> tuple[str, str]:
    """ISO date string ('2026-08-14') -> (start, end) ISO bounds for
    that calendar day, UTC. The one piece of date-handling logic this
    service owns; every query below reuses it rather than repeating
    its own bound computation."""
    start = datetime.fromisoformat(target_date).replace(tzinfo=timezone.utc)
    end = start + timedelta(days=1)
    return start.isoformat(), end.isoformat()


async def _events_for_day(project_id: str, start: str, end: str) -> list[dict]:
    return await db.events.find(
        {"project_id": project_id, "server_created_at": {"$gte": start, "$lt": end}},
        {"_id": 0},
    ).sort("server_created_at", -1).to_list(500)


async def _items_for_project(project_id: str) -> list[dict]:
    return await db.operational_items.find({"project_id": project_id}, {"_id": 0}).to_list(2000)


def _age_label(iso_ts: str) -> str:
    try:
        created = datetime.fromisoformat(iso_ts.replace("Z", "+00:00"))
        delta = datetime.now(timezone.utc) - created
        hours = delta.total_seconds() / 3600
        if hours < 24:
            return f"{int(hours)} hour{'s' if int(hours) != 1 else ''}"
        return f"{int(hours // 24)} day{'s' if int(hours // 24) != 1 else ''}"
    except Exception:
        return "unknown"


async def generate_daily_report(project_id: str, target_date: str, *, user: dict) -> dict:
    """The one entry point. Always generates the full internal report;
    client-safety is applied afterward via to_client_safe() as a pure
    view transformation, per this task's own explicit "implement as a
    view transformation, not a separate report-generation engine"
    rule — there is exactly one generation path, never two.
    """
    await commercial_engine.assert_project_visible(project_id, user)
    project = next((p for p in await memory_engine.list_projects(True, user=user) if p["id"] == project_id), None)
    start, end = _day_bounds(target_date)

    day_events = await _events_for_day(project_id, start, end)
    all_items = await _items_for_project(project_id)
    day_commercial_events = [e for e in await commercial_engine.list_commercial_events(project_id)
                             if start <= e["created_at"] < end]
    health = await reasoning_engine.explain_health(project_id, user=user)

    # ---- deterministic metrics (Section: Site Activity Snapshot) ----
    resolved_today = [i for i in all_items if i.get("closed_at") and start <= i["closed_at"] < end]
    open_blockers = [i for i in all_items if i.get("health") in ("blocked", "waiting_external")]
    new_blockers_today = [i for i in open_blockers if start <= i.get("created_at", "") < end]
    approvals_completed_today = [i for i in all_items if i.get("category") == "client_approval"
                                 and i.get("closed_at") and start <= i["closed_at"] < end]
    pending_approvals = [i for i in all_items if i.get("category") == "client_approval"
                         and i.get("status") not in ("closed", "fulfilled", "cancelled", "duplicate")]
    photos_today = sum(len(e.get("photo_asset_ids", [])) for e in day_events)

    metrics = {
        "new_capture_events": len(day_events),
        "operational_items_resolved": len(resolved_today),
        "new_blockers_raised": len(new_blockers_today),
        "approvals_completed": len(approvals_completed_today),
        "pending_approvals": len(pending_approvals),
        "photos_attached": photos_today,
    }

    # ---- Work Completed Today — real event text/kind, no fabrication ----
    work_completed = []
    for e in day_events:
        if e.get("text_input"):
            work_completed.append(e["text_input"][:160])
    for i in resolved_today:
        work_completed.append(i.get("title") or i.get("name") or "An item was resolved")

    # ---- Blockers & Risks ----
    blockers_section = []
    for b in open_blockers:
        entry = {
            "title": b.get("title") or b.get("name") or "Untitled item",
            "age": _age_label(b.get("created_at", "")),
            "impact_category": _CATEGORY_TO_IMPACT.get(b.get("category", "general"), "schedule"),
            "owner": b.get("assigned_to_user_name") or "Unassigned",
        }
        blockers_section.append(entry)

    # ---- Client Decisions Pending ----
    client_decisions = [
        {
            "title": i.get("title") or i.get("name") or "Untitled item",
            "requested_date": i.get("created_at", "")[:10],
            "pending_for": _age_label(i.get("created_at", "")),
        }
        for i in pending_approvals
    ]

    # ---- Commercial Attention (internal only, per this task's own client-safe rule) ----
    commercial_attention = []
    for e in day_commercial_events:
        if e["kind"] in ("payment_request_raised", "actual_cost_recorded", "budget_revised"):
            commercial_attention.append({"kind": e["kind"], "created_at": e["created_at"]})

    # ---- Executive Summary — deterministic template, not LLM prose ----
    exec_summary = _build_executive_summary(project, metrics, health, new_blockers_today, pending_approvals)

    # ---- AI Forecast Impact — deterministic rule + qualitative confidence, never a fabricated number ----
    forecast = _build_forecast_impact(open_blockers, health, day_commercial_events)

    # ---- Attached Photo Summary ----
    photo_events = [e for e in day_events if e.get("photo_asset_ids")]
    photo_summary = {
        "count": photos_today,
        "captions": [e.get("text_input", "")[:80] or "(no caption provided)" for e in photo_events[:5]],
        "thumbnail_note": "Thumbnail rendering not yet supported by the current UI — captions shown instead.",
    }

    return {
        "project_id": project_id,
        "project_name": project["name"] if project else "Unknown Project",
        "date": target_date,
        "client_safe": False,
        "executive_summary": exec_summary,
        "work_completed_today": work_completed[:10],
        "site_activity_snapshot": metrics,
        "blockers_and_risks": blockers_section,
        "client_decisions_pending": client_decisions,
        "commercial_attention": commercial_attention,
        "ai_forecast_impact": forecast,
        "attached_photo_summary": photo_summary,
        "health_status": health.get("status"),
        "generated_at": datetime.now(timezone.utc).isoformat(),
    }


def _build_executive_summary(project: Optional[dict], metrics: dict, health: dict,
                             new_blockers: list[dict], pending_approvals: list[dict]) -> str:
    """Deterministic template composition — every clause below is
    conditioned directly on a real computed value, never invented."""
    name = project["name"] if project else "this project"
    parts = [f"Site activity for {name}"]
    if metrics["new_capture_events"] == 0:
        parts.append("recorded no new capture events today.")
    else:
        parts.append(f"included {metrics['new_capture_events']} new capture event"
                     f"{'s' if metrics['new_capture_events'] != 1 else ''} today.")
    if new_blockers:
        parts.append(f"{len(new_blockers)} new blocker{'s' if len(new_blockers) != 1 else ''} "
                     f"{'were' if len(new_blockers) != 1 else 'was'} raised.")
    if pending_approvals:
        parts.append(f"{len(pending_approvals)} client decision{'s' if len(pending_approvals) != 1 else ''} "
                     f"remain{'s' if len(pending_approvals) == 1 else ''} pending.")
    status_label = {"green": "Healthy", "amber": "Moderate attention needed", "red": "Critical attention needed"}
    parts.append(f"Project health is currently {status_label.get(health.get('status'), 'Unknown')}.")
    return " ".join(parts)


def _build_forecast_impact(open_blockers: list[dict], health: dict, day_commercial_events: list[dict]) -> dict:
    """Deterministic rule, qualitative confidence only — per this
    task's own explicit "do not fabricate precise forecasts" rule. No
    day-count or cost-overrun number is ever invented; the only
    numbers used here are the real, already-computed open-blocker
    count and health status."""
    if not open_blockers:
        return {
            "statement": "No open blockers are currently affecting this project's schedule.",
            "confidence": "High confidence",
        }
    schedule_blockers = [b for b in open_blockers if _CATEGORY_TO_IMPACT.get(b.get("category", "general"), "schedule") == "schedule"]
    if schedule_blockers:
        statement = (
            f"{len(schedule_blockers)} open blocker{'s' if len(schedule_blockers) != 1 else ''} "
            f"with a schedule-impact category {'remain' if len(schedule_blockers) != 1 else 'remains'} unresolved. "
            f"If unresolved, near-term schedule activities dependent on this work may be delayed. No specific "
            f"day-count delay is estimated here, since Atlas does not yet track task dependency chains precisely "
            f"enough to compute one reliably."
        )
        confidence = "Moderate confidence" if health.get("status") != "green" else "Low confidence"
    else:
        statement = "Open blockers exist but none are currently categorized as schedule-impacting."
        confidence = "Moderate confidence"
    cost_signal = any(e["kind"] in ("actual_cost_recorded", "budget_revised") for e in day_commercial_events)
    if cost_signal:
        statement += " Commercial activity was recorded today — review the Bill phase for detail."
    else:
        statement += " No cost overrun signal is detected from today's activity."
    return {"statement": statement, "confidence": confidence}


def render_markdown(report: dict) -> str:
    """Render-ready markdown, per this task's own /export?format=md
    requirement. Pure formatting over the structured dict above — no
    new data, no new computation."""
    lines = [
        f"# Atlas Daily Site Report",
        f"**Project:** {report['project_name']}  ",
        f"**Date:** {report['date']}  ",
        f"**Mode:** {'Client-Safe' if report['client_safe'] else 'Internal'}",
        "",
        "## Executive Summary",
        report["executive_summary"],
        "",
        "## Work Completed Today",
    ]
    if report["work_completed_today"]:
        lines += [f"- {w}" for w in report["work_completed_today"]]
    else:
        lines.append("_No activity recorded for this date._")
    lines += ["", "## Site Activity Snapshot", "", "| Metric | Value |", "|---|---|"]
    metric_labels = {
        "new_capture_events": "New capture events", "operational_items_resolved": "Operational items resolved",
        "new_blockers_raised": "New blockers raised", "approvals_completed": "Approvals completed",
        "pending_approvals": "Pending approvals", "photos_attached": "Photos attached",
    }
    for key, label in metric_labels.items():
        lines.append(f"| {label} | {report['site_activity_snapshot'][key]} |")
    lines += ["", "## Blockers & Risks"]
    if report["blockers_and_risks"]:
        for b in report["blockers_and_risks"]:
            owner_line = f"  \nOwner: {b['owner']}" if "owner" in b else ""
            lines.append(f"- **{b['title']}**{owner_line}  \n  Open for: {b['age']}  \n  Potential impact: {b['impact_category'].replace('_', ' ').title()}")
    else:
        lines.append("_No open blockers._")
    lines += ["", "## Client Decisions Pending"]
    if report["client_decisions_pending"]:
        for c in report["client_decisions_pending"]:
            lines.append(f"- **{c['title']}** — requested {c['requested_date']}, pending {c['pending_for']}")
    else:
        lines.append("_Nothing pending._")
    if not report["client_safe"] and report["commercial_attention"]:
        lines += ["", "## Commercial Attention"]
        for c in report["commercial_attention"]:
            lines.append(f"- {c['kind'].replace('_', ' ').title()}")
    lines += ["", "## AI Forecast Impact", f"{report['ai_forecast_impact']['statement']}  \n*({report['ai_forecast_impact']['confidence']})*"]
    lines += ["", "## Attached Photo Summary", f"{report['attached_photo_summary']['count']} photo(s) captured today."]
    for cap in report["attached_photo_summary"]["captions"]:
        lines.append(f"- {cap}")
    if report["attached_photo_summary"]["count"] > 0:
        lines.append(f"_{report['attached_photo_summary']['thumbnail_note']}_")
    return "\n".join(lines)


def to_client_safe(report: dict) -> dict:
    """View transformation, not a separate generation path — per this
    task's own explicit "implement as a view transformation" rule.
    Takes an already-generated internal report and strips exactly the
    fields Section 5 names, rather than regenerating anything."""
    safe = dict(report)
    safe["client_safe"] = True
    safe["commercial_attention"] = []
    safe["blockers_and_risks"] = [
        {k: v for k, v in b.items() if k != "owner"} for b in report["blockers_and_risks"]
    ]
    return safe
