// KG-UI-01 — the Relationship Explorer. Every card here reuses KM-01's
// own, already-existing decision_trace/impact_trace responses and
// IN-01's own, already-existing deep-link URL shapes — no new backend
// call beyond what KM-01 already exposes, no graph/node visualization,
// per this task's own explicit "construction people think in stories,
// not graphs" rule.
import { useCallback, useEffect, useState } from 'react';
import { View, Text, StyleSheet, ScrollView, Pressable, ActivityIndicator } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { useRouter, useLocalSearchParams } from 'expo-router';
import { theme } from '@/src/theme';
import {
  apiGetDecisionTrace, apiGetImpactTrace,
  type DecisionTrace, type ImpactTrace, type GraphEdge,
} from '@/src/knowledge_graph_api';

const ENTITY_ICON: Record<string, any> = {
  event: 'camera-outline', variation: 'swap-horizontal', contract: 'document-text',
  milestone: 'flag', payment_request: 'receipt', payment: 'cash', project: 'business-outline',
  budget: 'wallet-outline', workflow_activity: 'hammer-outline', operational_item: 'construct-outline',
};

const RELATIONSHIP_VERB: Record<string, string> = {
  CAUSED: 'caused', MODIFIED: 'modified', GENERATED: 'generated', GENERATED_BY: 'was generated by',
  SETTLED_BY: 'was settled by', SETTLES: 'settles', BELONGS_TO: 'belongs to', EVIDENCES: 'evidences',
  DERIVED_FROM: 'was derived from',
};

// IN-01's own established deep-link URL shapes, reused exactly — this
// screen adds zero new navigation, only follows the paths IN-01
// already built.
function deepLinkFor(entityType: string, entityId: string, projectId?: string): string | null {
  if (!projectId) return null;
  switch (entityType) {
    case 'milestone': return `/commercial/${projectId}?action=edit-milestone&milestoneId=${entityId}`;
    case 'variation': return `/commercial/${projectId}?action=view-variation&variationId=${entityId}`;
    case 'payment_request': return `/commercial/${projectId}?action=record-payment&paymentRequestId=${entityId}`;
    case 'contract': return `/commercial/${projectId}?action=edit-contract`;
    case 'budget': return `/commercial/${projectId}?action=edit-budget`;
    default: return null;
  }
}

export default function ExplainScreen() {
  const router = useRouter();
  const { type, id, projectId } = useLocalSearchParams<{ type: string; id: string; projectId?: string }>();
  const [loading, setLoading] = useState(true);
  const [loadError, setLoadError] = useState<string | null>(null);
  const [decision, setDecision] = useState<DecisionTrace | null>(null);
  const [impact, setImpact] = useState<ImpactTrace | null>(null);

  const load = useCallback(async () => {
    if (!type || !id) return;
    setLoadError(null);
    try {
      const d = await apiGetDecisionTrace(type, id);
      setDecision(d);
      if (type === 'event') {
        const i = await apiGetImpactTrace(id).catch(() => null);
        setImpact(i);
      } else {
        setImpact(null);
      }
    } catch {
      setLoadError('Could not explain this record.');
    }
  }, [type, id]);

  useEffect(() => {
    (async () => { setLoading(true); await load(); setLoading(false); })();
  }, [load]);

  const openEntity = (entityType: string, entityId: string) => {
    if (entityType === 'event') { router.push(`/event/${entityId}`); return; }
    const url = deepLinkFor(entityType, entityId, projectId);
    if (url) router.push(url as any);
  };

  if (loading) {
    return <SafeAreaView style={styles.center} edges={['top']}><ActivityIndicator color={theme.color.brand} size="large" /></SafeAreaView>;
  }

  return (
    <SafeAreaView style={styles.container} edges={['top']}>
      <View style={styles.header}>
        <Pressable testID="explain-back" onPress={() => router.back()} hitSlop={12}>
          <Ionicons name="arrow-back" size={22} color={theme.color.text} />
        </Pressable>
        <Text style={styles.headerTitle}>Why does this exist?</Text>
        <View style={{ width: 22 }} />
      </View>

      <ScrollView contentContainerStyle={styles.content}>
        {loadError && <Text style={styles.errorText} testID="explain-load-error">{loadError}</Text>}

        {decision && decision.evidence.length > 0 && (
          <>
            <SectionLabel title="REASON" />
            {decision.evidence.map((edge) => (
              <StoryCard key={`${edge.entity_type}-${edge.entity_id}`} edge={edge} onPress={() => openEntity(edge.entity_type, edge.entity_id)} />
            ))}
          </>
        )}

        {decision && decision.commercial_events.length > 0 && (
          <>
            <SectionLabel title="WHAT HAPPENED" />
            {decision.commercial_events.slice(0, 8).map((e) => (
              <View key={e.id} style={styles.eventRow} testID={`explain-event-${e.id}`}>
                <View style={styles.eventDot} />
                <View style={{ flex: 1 }}>
                  <Text style={styles.eventText}>{e.kind.replace(/_/g, ' ')} — {e.actor_user_name}</Text>
                  <Text style={styles.eventTime}>{new Date(e.created_at).toLocaleString()}</Text>
                </View>
              </View>
            ))}
          </>
        )}

        {impact && impact.chain.length > 1 && (
          <>
            <SectionLabel title="WHAT THIS LED TO" />
            {impact.chain.slice(1).map((step, i) => (
              <StoryCard key={`${step.entity_type}-${step.entity_id}-${i}`}
                edge={{ entity_type: step.entity_type, entity_id: step.entity_id, label: step.label, relationship: step.via || '' }}
                onPress={() => openEntity(step.entity_type, step.entity_id)} />
            ))}
          </>
        )}

        {decision && decision.evidence.length === 0 && decision.commercial_events.length === 0 && !impact && (
          <Text style={styles.emptyText}>No connected history found for this record yet.</Text>
        )}
      </ScrollView>
    </SafeAreaView>
  );
}

function SectionLabel({ title }: { title: string }) {
  return <Text style={styles.sectionLabel}>{title}</Text>;
}

function StoryCard({ edge, onPress }: { edge: GraphEdge; onPress: () => void }) {
  const icon = ENTITY_ICON[edge.entity_type] || 'ellipse-outline';
  const verb = RELATIONSHIP_VERB[edge.relationship] || edge.relationship.toLowerCase();
  return (
    <Pressable testID={`explain-card-${edge.entity_type}-${edge.entity_id}`} onPress={onPress} style={styles.card}>
      <Ionicons name={icon} size={20} color={theme.color.brand} />
      <View style={{ flex: 1, marginLeft: 10 }}>
        <Text style={styles.cardLabel}>{edge.label}</Text>
        <Text style={styles.cardVerb}>{verb}</Text>
      </View>
      <Ionicons name="chevron-forward" size={16} color={theme.color.textDim} />
    </Pressable>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: theme.color.surface },
  center: { flex: 1, backgroundColor: theme.color.surface, alignItems: 'center', justifyContent: 'center' },
  header: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    paddingHorizontal: theme.spacing.lg, paddingVertical: theme.spacing.md,
  },
  headerTitle: { color: theme.color.text, fontSize: 16, fontWeight: '800' },
  content: { padding: theme.spacing.md, paddingBottom: 40 },
  errorText: { color: theme.color.error, marginBottom: theme.spacing.sm },
  emptyText: { color: theme.color.textDim, fontSize: 13, fontStyle: 'italic', marginTop: theme.spacing.lg },
  sectionLabel: {
    color: theme.color.textDim, fontSize: 11, fontWeight: '800', letterSpacing: 1,
    marginTop: theme.spacing.lg, marginBottom: theme.spacing.sm,
  },
  card: {
    flexDirection: 'row', alignItems: 'center', backgroundColor: theme.color.surface2,
    borderRadius: theme.radius.md, borderWidth: 1, borderColor: theme.color.border,
    padding: theme.spacing.md, marginBottom: theme.spacing.sm,
  },
  cardLabel: { color: theme.color.text, fontSize: 14, fontWeight: '700' },
  cardVerb: { color: theme.color.textDim, fontSize: 12, marginTop: 2, textTransform: 'capitalize' },
  eventRow: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 6 },
  eventDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: theme.color.textDim },
  eventText: { color: theme.color.text, fontSize: 13, textTransform: 'capitalize' },
  eventTime: { color: theme.color.textDim, fontSize: 11, marginTop: 1 },
});
